In [1]:
import numpy as np

In [3]:
arr=np.array([23,45,12,67,34])

In [4]:
print(arr)

[23 45 12 67 34]


In [5]:
arr

array([23, 45, 12, 67, 34])

In [6]:
arr=np.array([23,45,12,67,34,12.13])

In [7]:
print(arr)

[23.   45.   12.   67.   34.   12.13]


In [8]:
arr

array([23.  , 45.  , 12.  , 67.  , 34.  , 12.13])

In [9]:
arr.dtype

dtype('float64')

In [18]:
arr1=np.array([23,45,12,67,34,12.13,'pune'])

In [19]:
arr1

array(['23', '45', '12', '67', '34', '12.13', 'pune'], dtype='<U32')

In [20]:
arr1.dtype

dtype('<U32')

In [21]:
arr1[2]

'12'

In [22]:
%%timeit
arr=np.array([23,45,12,67,34,12.13])

1.52 µs ± 97.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
arr

array(['23', '45', '12', '67', '34', '12.13', 'pune'], dtype='<U32')

In [24]:
arr.ndim

1

In [26]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [28]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
np.arange(2,21,0.5)

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. ,
       18.5, 19. , 19.5, 20. , 20.5])

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
#2dimenshional array


arr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [42]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
arr2.shape

(4, 3)

In [44]:
arr2.size

12

In [45]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
arr2.ndim

2

In [47]:
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
arr2.shape

(4, 3)

In [49]:
arr2.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
arr2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [52]:
arr2.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [57]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [58]:
arr2.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [59]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [67]:
arr2[0:3,0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2[0:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr

array(['23', '45', '12', '67', '34', '12.13', 'pune'], dtype='<U32')

In [70]:
arr=np.array([1,2,2,3,3,4,4,5,6])

In [71]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [72]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [73]:
np.linalg.inv(arr3)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [75]:
arr2 @ arr3

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150],
       [138, 171, 204]])